### PR TITLE
Fix expiration of counters

### LINKED ISSUE #71: counters never call updated
It looks like all counters expire after 15m and never come back. I think the problem is the counter doesn't call the `Updated` method on the base meter type:

https://github.com/Netflix-Skunkworks/atlas-native-client/blob/master/meter/default_counter.h

Gauges do report fine, but they call updated:

https://github.com/Netflix-Skunkworks/atlas-native-client/blob/master/meter/default_gauge.cc#L24

### PR DESCRIPTION
**Pull request by dmuino**
Fixes #71, and adds a couple of test cases to ensure it stays fixed.

### CODE REVIEW

File: test/default_timer_test.cc [hunk 1]
```diff
@@ -80,3 +80,25 @@ TEST(DefaultTimer, Measure) {
     }
   }
 }
+
+TEST(DefaultTimer, Expiration) {
```
Comment (brharrington) [inline test/default_timer_test.cc]: Does it make sense to add this for distribution summaries as well?

File: meter/default_timer.cc [hunk 2]
```diff
@@ -28,8 +28,8 @@ void DefaultTimer::Record(std::chrono::nanoseconds nanos) {
         static_cast<double>(nanos_count) * static_cast<double>(nanos_count);
     sub_total_sq_.Add(nanos_sq);
     sub_max_.Update(nanos_count);
-    Updated();
   }
+  Updated();
```
Comment (brharrington) [inline meter/default_timer.cc]: What about distribution summaries?
